### ISSUE TITLE
Add boost as vcpkg dependency

### ISSUE THREAD

**Issue by Nicogene** [robotology/robotology-superbuild-dependencies-vcpkg#7]
It is possible to add `boost` as vcpkg dependency?

The project where it is needed is https://github.com/robotology/blocktest.

**Comment by traversaro** [comment]
Which ports in particular? Given that the users can install their own ports after unzip the binary archive provided here or the vcpkg installation under `C:\robotoogy\vcpkg` installed by https://github.com/robotology/robotology-superbuild/releases/tag/v2020.02, ideally we should limit the port pre-installed just to the one actually used. By giving a short glance to the headers (https://github.com/robotology/blocktest/search?p=2&q=boost&type=) it seems that may be necessary: 
* boost-asio 
* boost-dll 
* boost-bind
* boost-smart-ptr 
* boost-filesystem 
* boost-process 

However, in the meanwhile for CI I suggest you to use the existing binary archive (as done in https://github.com/robotology/robotology-superbuild/blob/master/.github/workflows/ci.yml#L96) so that you don't need to compile heavy ports such as `qt5-base` and `qt5-declerative` and then add the additional ports that you need by simply running: 
~~~
C:/robotology/vcpkg/vcpkg.exe --install boost-asio boost-dll boost-bind boost-smart-ptr boost-filesystem boost-process 
~~~

By the way, for smart ptr there is any reason why the boost data structures instead of the equivalent one supported in standard C++ since C++11? 

cc @pattacini @vtikha

**Comment by pattacini** [comment]
`blocktest` is not delivered through our distro - yet at least - so I'd say that @traversaro 's suggestion to add up `vcpkg` ports after one has installed the distro could be a viable solution as of now.

**Comment by Nicogene** [comment]
> Which ports in particular?

I think that `boost-filesystem`, `boost-system` should be enough, if it exists also `boost-process` 


> By the way, for smart ptr there is any reason why the boost data structures instead of the equivalent one supported in standard C++ since C++11?

We should use the standard one, this component should be not necessary thou.

**Comment by traversaro** [comment]
> 
> > Which ports in particular?
> 
> I think that `boost-filesystem`, `boost-system` should be enough, if it exists also `boost-process`.
> I mean about my request, I don't know in general.
> Asio also will be useful for diagnostics, but it will run only on linux I suppose

Sorry, I was not clear. If you follow the link https://github.com/robotology/blocktest/search?p=2&q=boost&type= by inspecting the source code is seems that all the one that I listed seems to be necessary. 

> > By the way, for smart ptr there is any reason why the boost data structures instead of the equivalent one supported in standard C++ since C++11?
> 
> We should use the standard one, this component should be not necessary thou.

Apparently that is not the case: https://github.com/robotology/blocktest/blob/ca4b4cfc39bf63ad008bdcede94cf7d3ecca21ed/src/blocktestrunner/connection.cpp#L6 .

**Comment by Nicogene** [comment]
@traversaro here is the list of vcpkg that `blocktest` need:
```
boost-system boost-filesystem \
boost-process boost-asio boost-dll
```

**Comment by traversaro** [comment]
@Nicogene @pattacini @vtikha How do you want to proceed with this request? We can  try to do it in time for 2020.05, or delay it to after 2020.05 to target  2020.08 .

**Comment by pattacini** [comment]
I've no particular opinion on that. We could include it if there's time left.

**Comment by traversaro** [comment]
> 
> 
> I've no particular opinion on that. We could include it if there's time left.

Adding it is  not particular  time consuming, I can easily do it while I updated the repo for  trying to fix the Qt5 issues (https://github.com/robotology/robotology-superbuild/issues/354). If we all agree on adding them, I can do it with no problems.

**Comment by pattacini** [comment]
Fine with me then 👍

**Comment by Nicogene** [comment]
I agree adding it in the 2020.05 release if it is not a big deal

**Comment by traversaro** [comment]
> I agree adding it in the 2020.05 release if it is not a big deal

This is already part of https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/14 . The PR is a bit "fat" because the CI time is quite big and so I preferred to but a few changes together, but if you could review we are good to go.
